# Generated by Django 6.0.7 on 2026-07-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0002_department_alter_supervisorrequest_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='department',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='supervisorrequest',
            name='status',
        ),
        migrations.AlterField(
            model_name='supervisorrequest',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
