# Generated by Django 6.0.6 on 2026-08-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0007_alter_supervisorrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorrequest',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='supervisorrequest',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
